INSERT INTO PRODUCTS (PRODUCTID,PRODUCTNAME,PRICE,CATEGORY) VALUES (1,'BASKET',100,'GROCERY');
INSERT INTO PRODUCTS (PRODUCTID,PRODUCTNAME,PRICE,CATEGORY) VALUES (2,'BOOK',100,'STUDY');
INSERT INTO PRODUCTS (PRODUCTID,PRODUCTNAME,PRICE,CATEGORY) VALUES (3,'PEN',100,'STUDY');
INSERT INTO PRODUCTS (PRODUCTID,PRODUCTNAME,PRICE,CATEGORY) VALUES (4,'PENCIL',100,'STUDY');
INSERT INTO PRODUCTS (PRODUCTID,PRODUCTNAME,PRICE,CATEGORY) VALUES (5,'BALL',100,'GROCERY');